networks:
  mynetwork:

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - mynetwork
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    networks:
      - mynetwork

  orchestrator:
    build: ./orchestrator
    ports:
      - "8001:8001"
    depends_on:
      - kafka
    networks:
      - mynetwork

  runner:
    build: ./runner
    ports:
      - "8002:8002"
    depends_on:
      - kafka
    networks:
      - mynetwork
    volumes:
      - ./videos:/videos

  inference:
    build: ./inference
    ports:
      - "8003:8003"
    depends_on:
      - kafka
    networks:
      - mynetwork
    volumes:
      - ./videos:/videos